baseurl: ''
permalink: pretty
title: 'Ejby Badminton'
theme: null

lang: 'da'

description: 'Ejby Badminton Klub — Badminton for alle!'

author:
  name: 'William Bergmann Børresen'
  email: 'wbb@ejbyif-badminton.dk'

url: 'https://ejbyif-badminton.dk'

collections_dir: indhold/sider
data_dir: indhold/data

logo:
  mobile: "/images/logo/ejby_if_logo.png"
  mobile_height: 100
  mobile_width: 100
  desktop: "/images/logo/ejby_if_logo.png"
  desktop_height: 100
  desktop_width: 100

home: 
  limit_services: 6

collections:
  tilbud:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "tilbud"
    values:
      layout: "service"
  - scope:
      path: ""
    values:
      image: "/images/logo/ejby_if_logo.png"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
