module.exports = {
  // Purge the compiled stylesheet (generated by Jekyll into _site)
  css: ["_site/assets/css/style.css"],

  // Scan rendered HTML (and JS) for used selectors/classes
  content: ["_site/**/*.html", "_site/assets/js/**/*.js"],

  // Write back into the same folder (overwriting style.css)
  output: "_site/assets/css/",

  // Keep common dynamic/state classes and our component prefixes.
  // This is intentionally conservative to avoid breaking styling.
  safelist: {
    standard: [
      "active",
      "show",
      "open",
      "has-dropdown",
      "visually-hidden",
    ],
    greedy: [
      /^page-/, 
      /^main-menu/, 
      /^hamburger/, 
      /^intro/, 
      /^strip/, 
      /^service/, 
      /^feature/, 
      /^button/, 
      /^sponsors-/, 
      /^dropdown-/, 
      /^col-/, 
      /^row$/, 
      /^container$/,
      /^pt-/, /^pb-/, /^mt-/, /^mb-/, /^mx-/, /^my-/, /^px-/, /^py-/
    ],
  },
};
